---
title: "Species vulnerability - match assessed to spatial"
author: "Casey O'Hara"
date: "5/18/2020"
output: html_document
---

```{r setup, include=FALSE}
source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')
```

Prep AquaMaps list for matching

```{r}
am_spp_raw <- read_csv('speciesoccursum_ver0816c.csv', col_types = cols(.default = 'c')) %>%
  janitor::clean_names() %>%
  select(am_sid = speciesid, comname = f_bname, 
         kingdom:family, genus, species) %>%
  distinct()

ranks <- names(am_spp %>% select(-am_sid, -comname))

am_match <- am_spp_raw %>%
  gather(rank, name, kingdom:species) %>%
  mutate(rank = factor(rank, levels = ranks),
         name = tolower(name))
  
```

prep spp vulnerability list for matching

``` {r}
sv_spp <- read_csv('Supplementary_Information.csv', col_types = cols(.default = 'c')) %>%
  janitor::clean_names() %>%
  select(gp_name = common_name, 
         kingdom, phylum, class, order, 
         family = family_superfamily, genus, species)

### let's assume unique matches for rank names for now?
sv_match <- sv_spp %>%
  gather(rank, name, kingdom:species) %>%
  mutate(name = str_split(name, '[^A-Za-z]+'),
         rank = factor(rank, levels = ranks)) %>%
  unnest(name) %>%
  filter(!is.na(name)) %>%
  mutate(name = tolower(name)) %>%
  group_by(gp_name) %>%
  mutate(rank_match = ranks[max(as.integer(rank))]) %>%
  filter(rank == rank_match) %>%
  select(-rank_match)

### fix some mismatches - typos/alt names?
name_fix <- c('cnideria'       = 'cnidaria',
              'chelonioidea'   = 'cheloniidae',
              # 'aves'         = NA,
              'artiodactyla' = 'cetacea',
              # 'gobiformes'   = 'perciformes', # convert to class gobiidae?
              # 'phytoplankton' = NA,
              # 'zooplankton'  = NA,
              'demospongia'    = 'demospongiae',
              'chondrichthyes' = 'elasmobranchii')

sv_match_fixed <- sv_match %>%
  mutate(rank = as.character(rank),
         rank = ifelse(name == 'gobiformes', 'family', rank),
         name = ifelse(name == 'gobiformes', 'gobiidae', name),
         rank = factor(rank, levels = ranks)) %>%
  mutate(name = ifelse(name %in% names(name_fix),
                       name_fix[name], name))
  
```

match 'em up?

```{r}
match_df <- sv_match_fixed %>%
  left_join(am_match, by = c('name', 'rank'))

match_table <- match_df %>%
  group_by(gp_name) %>%
  summarize(n_spp = n_distinct(am_sid, na.rm = TRUE)) %>%
  left_join(sv_spp, by = 'gp_name')

knitr::kable(match_table)
```

